### ISSUE TITLE
Remove master Pipfile: replace with sub project Pipfiles

### ISSUE THREAD

**Issue by rianders** [fubarlabs/foocars#36]
Remove master Pipfile: replace with sub project Pipfiles

**Comment by rianders** [comment]
Projects needing Pipfiles:

[ ] Remove top level Pipfile
[x ] Add ./train Pipfile 
[ ] Curator
[ ] Car Pipfile

Any more add to the list.

**Comment by ricklon** [comment]
Removed the need for the top level Pipfile. File removed.

**Comment by ricklon** [comment]
Oops. More to do.

**Comment by ricklon** [comment]
We've moved the project from Pipenv to Poetry.
