### ISSUE TITLE
curator depends on scipy.misc causes error

### ISSUE THREAD

**Issue by ricklon** [fubarlabs/foocars#40]
Curator depends on scipy.misc which causes a crash error. The default version is 0.18.

Quick fix:
```
sudo pip3 install scipy==0.15
```

**Comment by MC42** [comment]
This was fixed in a PR by removing scipy entirely and replacing it with a native numpy operation.

Docs here: https://docs.scipy.org/doc/scipy-1.2.1/reference/generated/scipy.misc.imresize.html

**Comment by ricklon** [comment]
This dependency is confirmed fixed.
